# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Cora Barrett
email: coralouisebarrett@gmail.com
description: >
  This is a website by Cora Barrett discussing her musings on UK property planning.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://corabarrett.com"

# Footer settings
footer: Cora Barrett

# Social networks
social:
  - title: facebook
    url: https://www.facebook.com/cora.barrett.12
  - title: linkedin
    url: https://www.linkedin.com/in/corabarrett/
  - title: github
    url: https://github.com/corabarrett

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# Default layouts for pages
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      author: "Cora Barrett"
      published: true
