# Site settings
title: Cora Barrett
email: coralouisebarrett@gmail.com
url: ""
description: |
  Welcome to my website

# Footer settings
footer: Cora Barrett

# Social networks
social:
  # - title: twitter
  #   url: https://twitter.com/ayoungersage
  # - title: facebook
  #   url: https://facebook.com/sam.younger1
  # - title: stack-overflow
  #   url: http://stackoverflow.com/story/samyounger
  # - title: linkedin
  #   url: http://linkedin.com/in/sam-younger
  - title: github
    url: https://github.com/corabarrett

# Build settings
markdown: kramdown
permalink: pretty
