title: Cora Barrett
email: coralouisebarrett@gmail.com
description: >
  This is a website by Cora Barrett describing his path to becoming a web developer, and a blog discussing web development learning.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://corabarrett.com"
twitter_username: ayoungersage
github_username:  corabarrett

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
